### ISSUE TITLE
Peer to peer code review 

### ISSUE THREAD

**Issue by tugsem** [Mikelobi/Capstone-Project#4]
## Nice job so far 🎯 Here are little suggestions to improve on : 
-  There are some javascript errors in the console. Please try to fix that .
(Uncaught TypeError: Cannot read properties of null (reading 'appendChild')
    at App.js:157:16)
- On both the main and about page, you have an overflow-x. Kindly set that to hidden. It's one of the best practices of HTML and CSS.
- On the mobile version, please decrease the size of images in the featured speakers section.
- On the mobile version, please make the font size of 'Partners' bigger.
- On desktop version, navigation menu wraps when you decrease screen size. Please set that item to 'flex-wrap: nowrap;'.
-  This is optional , but adding some hover effect on the cards would look nice.

**Comment by Mikelobi** [comment]
Ok Team, I will make the changes.

**Comment by Mikelobi** [comment]
@tugsem thanks
